Repository AY2223S1-CS2103T-W17-2/tp, pull requests merged in 2022-11, with the labels that each got.

#159 Fix direct copying of string value
  src/main/java/seedu/pennywise/model/entry/Amount.java
Labels: bug

#160 Fix broken links in guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#158 More UG improvements
  docs/UserGuide.md
  src/main/resources/view/HelpWindow.fxml
Labels: documentation

#163 Add UG fixes for PED issues
  docs/UserGuide.md
Labels: documentation

#168 UserGuide: Specify default view
  docs/UserGuide.md
Labels: documentation, type.userguide

#169 Fix amount overflow
  src/main/java/seedu/pennywise/logic/parser/ParserUtil.java
  src/main/java/seedu/pennywise/model/entry/Amount.java
  src/main/java/seedu/pennywise/storage/JsonAdaptedEntry.java
  src/test/java/seedu/pennywise/model/entry/AmountTest.java
Labels: bug

#171 Fix DG bugs
  README.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditEntrySequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UpdatedUIClassDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditEntrySequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/PennyWiseLogo.png
  docs/images/UiClassDiagram.png
  docs/images/UpdatedUIClassDiagram.png
  docs/images/ViewActivityDiagram.png
  src/main/java/seedu/pennywise/ui/EntryCard.java
  src/main/resources/view/EntryListCard.fxml
Labels: documentation, type.devguide

#175 Update Ruihan's PPP
  docs/team/ruihan00.md
Labels: documentation

#166 Add Emily's PPP draft
  docs/team/emilyong.md
Labels: documentation

#176 Minor edits to UG
  docs/UserGuide.md
Labels: documentation

#173 DeveloperGuide: Add effort
  docs/DeveloperGuide.md
Labels: documentation, type.devguide

#164 Add examples for each feature + minor edits
  docs/UserGuide.md
Labels: type.userguide

#181 Documentation: Add touch up and fix typos
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/SummarySequenceDiagram.puml
  docs/diagrams/ViewActivityDiagramBusiness.puml
  docs/images/AddSequenceDiagram.png
  docs/images/SummarySequenceDiagram.png
  docs/images/ViewActivityDiagramBusiness.png
  docs/images/ug/ChartLegend.png
  docs/images/ug/LineGraphDates.png
  docs/images/ug/MacUnidentifiedDeveloper.png
  docs/images/ug/ViewCommandExpenditureMonth.png
Labels: documentation

#188 Standardise PPP
  docs/team/emilyong.md
Labels: documentation

#190 UserGuide: Fix minor typos
  docs/UserGuide.md
  src/main/java/seedu/pennywise/logic/commands/ViewCommand.java
Labels: documentation
