Repository AY2223S1-CS2103T-W17-2/tp, pull requests merged in 2022-10, with the labels that each got.

#30 Spendings Functionality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyPennyWise.java
  src/main/java/seedu/address/model/entry/Amount.java
  src/main/java/seedu/address/model/entry/Date.java
  src/main/java/seedu/address/model/entry/Description.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/main/java/seedu/address/model/entry/Expenditure.java
  src/main/java/seedu/address/model/entry/exceptions/DuplicateEntryException.java
  src/main/java/seedu/address/model/entry/exceptions/EntryNotFoundException.java
  src/main/java/seedu/address/model/expenditure/Amount.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Description.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniqueEntryList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.story

#33 View `Expenditure` and `Income` entries
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/entry/Amount.java
  src/main/java/seedu/address/model/entry/EntryType.java
Labels: type.story

#35 Refactor Person object to Entry Object, modified commands to work for new Entry Object
  .gitattributes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyPennyWise.java
  src/main/java/seedu/address/model/entry/Amount.java
  src/main/java/seedu/address/model/entry/Date.java
  src/main/java/seedu/address/model/entry/Description.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/main/java/seedu/address/model/entry/Expenditure.java
  src/main/java/seedu/address/model/entry/exceptions/DuplicateEntryException.java
  src/main/java/seedu/address/model/entry/exceptions/EntryNotFoundException.java
  src/main/java/seedu/address/model/expenditure/Amount.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Description.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniqueEntryList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.story

#31 Update UI: title, user guide link, pie chart panel
  README.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueEntryList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/ui/EntryPane.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PieChartPanel.java
  src/main/resources/images/pie_chart.png
  src/main/resources/view/EntryPane.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PieChartPanel.fxml
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.ui

#36 Summarising Financials
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SummaryCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/Amount.java
  src/main/java/seedu/address/model/entry/Date.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/main/java/seedu/address/model/entry/EntryType.java
  src/main/java/seedu/address/model/entry/Expenditure.java
  src/main/java/seedu/address/model/expenditure/Amount.java
  src/main/java/seedu/address/model/expenditure/Date.java
  src/main/java/seedu/address/model/expenditure/Expenditure.java
  src/main/java/seedu/address/model/person/UniqueEntryList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAdaptedExpenditure.java
  src/main/java/seedu/address/storage/JsonAdaptedIncome.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/entry/AmountTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ExpenditureBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalEntry.java
Labels: type.story

#43 Add Edit Entries functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEntryDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditEntryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.story

#64 Fix Edit Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/testutil/ExpenditureBuilder.java
Labels: bug

#72 fix bug in add command test
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#75 enable assertions in build.gradle
  build.gradle
Labels: enhancement

#70 Refactor DG for AddressBook -> PennyWise cleanup + AddCommand Implementation DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: documentation

#68 Update developer guide
  .gitattributes
  docs/DeveloperGuide.md
  docs/diagrams/PieChartViewSequenceDiagram.puml
  docs/diagrams/UpdatedUI.puml
  docs/images/PieChartViewSequenceDiagram.png
  docs/images/UpdatedUIClassDiagram.png
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.devguide

#83 Fix `Edit` command and tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: bug

#82 DeveloperGuide: Fix diagrams, typos and add EditCommand diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/PieChartViewSequenceDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/PieChartViewSequenceDiagram.png
  docs/images/ViewActivityDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/entry/Entry.java
Labels: documentation, type.devguide

#87 Display placeholder text when there is no entry found for charts & fix
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/main/java/seedu/address/ui/EntryLineChart.java
  src/main/java/seedu/address/ui/EntryPieChart.java
  src/main/java/seedu/address/ui/GraphPanel.java
  src/main/java/seedu/address/ui/NoEntryFound.java
  src/main/resources/view/GraphPanel.fxml
  src/main/resources/view/NoEntryFound.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalEntry.java
  src/test/java/seedu/address/testutil/TypicalLineChartData.java
Labels: bug, enhancement

#91 add unqiueEntryListTest
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/entry/DateTest.java
  src/test/java/seedu/address/model/entry/UniqueEntryListTest.java
Labels: priority.MEDIUM

#90 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UserInterfaceExplaination.png
Labels: documentation

#103 Simplify view command
  docs/UserGuide.md
  src/main/java/seedu/pennywise/logic/commands/ViewCommand.java
  src/main/java/seedu/pennywise/logic/parser/CliSyntax.java
  src/main/java/seedu/pennywise/logic/parser/ViewCommandParser.java
  src/main/resources/view/Extensions.css
  src/test/java/seedu/pennywise/logic/commands/CommandTestUtil.java
  src/test/java/seedu/pennywise/logic/commands/ViewEntriesDescriptorTest.java
  src/test/java/seedu/pennywise/logic/parser/PennyWiseParserTest.java
  src/test/java/seedu/pennywise/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/pennywise/testutil/ViewEntriesDescriptorBuilder.java
Labels: bug

#109 edit index.md
  docs/index.md
Labels: documentation

#104 Update user guide with more user-friendly text
  docs/SettingUp.md
  docs/UserGuide.md
  docs/images/AddCommand1.png
  docs/images/AddCommand2.png
  docs/images/DeleteCommand1.png
  docs/images/DeleteCommand2.png
  docs/images/EditCommand1.png
  docs/images/EditCommand2.png
  docs/images/SummaryCommand1.png
  docs/images/Ui.png
  docs/images/UserInterfaceExplaination.png
  docs/images/ViewCategory1.png
  docs/images/ViewCategory2.png
  docs/images/ViewMonth1.png
  docs/images/ViewMonth2.png
  docs/images/ug/AddCommandExpenditure.png
  docs/images/ug/AddCommandIncome.png
  docs/images/ug/DeleteCommandExpenditure.png
  docs/images/ug/DeleteCommandIncome.png
  docs/images/ug/EditCommandExpenditure.png
  docs/images/ug/EditCommandIncome.png
  docs/images/ug/SummaryCommand.png
  docs/images/ug/SummaryCommandMonth.png
  docs/images/ug/UserInterfaceExplanation.png
  docs/images/ug/ViewCommandExpenditureCategory.png
  docs/images/ug/ViewCommandExpenditureMonth.png
  docs/index.md
Labels: documentation, type.userguide

#146 Add default date for add command
  docs/UserGuide.md
  src/main/java/seedu/pennywise/logic/parser/AddCommandParser.java
  src/main/java/seedu/pennywise/model/entry/Date.java
  src/test/java/seedu/pennywise/logic/parser/AddCommandParserTest.java
Labels: bug

#152 Fix chart legend bug
  docs/UserGuide.md
  docs/images/ug/ChartLegend.png
  docs/images/ug/LineGraphDates.png
  src/main/resources/view/Extensions.css
Labels: bug

#155 Fix amount cutoff
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: bug
