Repository AY2223S1-CS2103T-W17-2/tp, pull requests merged in 2022-09, with the labels that each got.

#14 Edit user stories in developer guide
  docs/DeveloperGuide.md
Labels: type.devguide

#12 Update UserGuide.md for intro and contents
  docs/UserGuide.md
Labels: type.userguide

#13 Update UG and DG and added PPP and Profile Picture
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/jasonyapzx.png
  docs/team/jasonyapzx.md
Labels: type.userguide, type.devguide

#23 Developer Guide: Add non-functional requirements
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.devguide

#28 Update AboutUs
  docs/AboutUs.md
Labels: type.userguide
